/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib_project;

import Controller.DAO_ChiTietPhieuMuon;
import Object.DocGia;
import Object.PhieuMuon;
import Object.Sach;
import java.awt.event.ItemEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phuong Thang
 */
public class fMuonSach extends javax.swing.JFrame {

    ArrayList<DocGia> listDocGia = new ArrayList<>();
    ArrayList<Sach> listSach = new ArrayList<>();
    ArrayList<PhieuMuon> list = new ArrayList<>();
    int indexcbSelected = 0;
    DefaultTableModel model;
    DefaultTableModel model1;
    int checkout = 0;
    public fMuonSach() {
        initComponents();
        getDate();
        model = (DefaultTableModel) tableHienThi.getModel();
        model1 = (DefaultTableModel) tableChiTietPhieuMuon.getModel();
        long now = Instant.now().toEpochMilli();
        txtMaPhieuMuon.setText("PM"+String.valueOf(now));
        resize();
        setEnable(false);
        btnNhapTiep.setEnabled(false);
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnTimKiem.setEnabled(false);
        cbLuaChon.setEnabled(false);
        btnLuu.setEnabled(false);
        txtMaDocGia.setEditable(false);
        txtTenDocGia.setEditable(false);
        txtMaSach.setEditable(false);
        txtTenSach.setEditable(false);
        
    }
    public final void setEnable(boolean check)
    {
        txtMaDocGia.setEnabled(check);
        txtTenDocGia.setEnabled(check);
        txtMaSach.setEnabled(check);
        txtTenSach.setEnabled(check);
        txtTimKiem.setEnabled(check);
    }
    public final void getDate()
    {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");                                                                                           
        txtNgayMuon.setText(sdf.format(date));
        txtNgayTra.setText(sdf.format(date));
    }
    public final void getData(String sophieumuon)
    {
        model1.setNumRows(0);
        list = new DAO_ChiTietPhieuMuon().getListPhieuMuon(sophieumuon);
        int i = 1;
        for(PhieuMuon obj:list)
        {
            model1.addRow(new Object[]{
            i++, obj.getMaphieumuon(),obj.getMadocgia(),obj.getTendocgia(),obj.getNgaymuon(),obj.getNgaytra(),obj.getMasach(),obj.getTensach()
            });
        }
    }
    public final void resize()
    {
                tableHienThi.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
                tableHienThi.getColumnModel().getColumn(0).setPreferredWidth(45);
                tableHienThi.getColumnModel().getColumn(1).setPreferredWidth(150);
                tableHienThi.getColumnModel().getColumn(2).setPreferredWidth(170);
                tableHienThi.getColumnModel().getColumn(3).setPreferredWidth(120);
                tableHienThi.getColumnModel().getColumn(4).setPreferredWidth(100);
                tableHienThi.getColumnModel().getColumn(5).setPreferredWidth(160);
                tableHienThi.getColumnModel().getColumn(6).setPreferredWidth(135);
                tableHienThi.getColumnModel().getColumn(7).setPreferredWidth(115);
    }
    public final  void clearText()
    {
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtTimKiem.setText("");
        model.setNumRows(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaPhieuMuon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayMuon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaDocGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTenDocGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHienThi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChiTietPhieuMuon = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        cbLuaChon = new javax.swing.JComboBox<>();
        txtTenSach = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        btnNhapTiep = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mượn Sách");

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jPanel2.setBackground(new java.awt.Color(230, 136, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mượn Sách");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/zip-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(534, 534, 534))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã phiếu mượn :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã sách :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên sách :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ngày mượn :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày trả :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mã độc giả :");

        txtMaDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tên độc giả :");

        txtTenDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tìm kiếm :");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã độc giả", "Tên độc giả", "Ngày sinh", "Giới tính", "Địa chỉ", "Số điện thoại", "Nhóm"
            }
        ));
        tableHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHienThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHienThi);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tạo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(204, 204, 255));
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tableChiTietPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu mượn", "Mã độc giả", "Tên độc giả", "Ngày mượn", "Ngày trả", "Mã sách", "Tên sách"
            }
        ));
        tableChiTietPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableChiTietPhieuMuonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableChiTietPhieuMuon);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lựa chọn :");

        cbLuaChon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Độc giả", "Sách" }));
        cbLuaChon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLuaChonItemStateChanged(evt);
            }
        });

        txtTenSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtMaSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnNhapTiep.setBackground(new java.awt.Color(52, 152, 219));
        btnNhapTiep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhapTiep.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapTiep.setText("Nhập tiếp");
        btnNhapTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapTiepActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 51, 51));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 102, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(46, 204, 113));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 204, 204));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(51, 153, 255));
        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTimKiem)
                                    .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNhapTiep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(63, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem)
                            .addComponent(jLabel9)
                            .addComponent(btnThoat))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNhapTiep))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSua)
                                        .addComponent(btnXoa))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThem)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnLuu)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String truyvan = txtTimKiem.getText();
        indexcbSelected = cbLuaChon.getSelectedIndex();
        if(indexcbSelected == 0)
        {
            listDocGia = new DAO_ChiTietPhieuMuon().TimDocGia(truyvan);
            model.setNumRows(0);
            int i = 1;
            for(DocGia obj:listDocGia)
            {
                model.addRow(new Object[]{
                i++, obj.getMadocgia(),obj.getTendocgia(),obj.getNgaysinh(),obj.getGioitinh(),obj.getDiachi(),obj.getSdt(),obj.getNhom()
                });
            }
        }else if(indexcbSelected == 1)
        {
            listSach = new DAO_ChiTietPhieuMuon().TimSach(truyvan);
            model.setNumRows(0);
            int i = 1;
            for(Sach obj:listSach)
            {
                model.addRow(new Object[]{
                i++, obj.getMasach(),obj.getTensach(),obj.getTentacgia(),obj.getNoixuatban(),obj.getNamxuatban(),obj.getLoai()
                });
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tableHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHienThiMouseClicked
       int id = tableHienThi.getSelectedRow();
        if(id>=0)
        {
            if(indexcbSelected == 0)
            {
                txtMaDocGia.setText((String) model.getValueAt(id, 1));
                txtTenDocGia.setText((String) model.getValueAt(id, 2));
                cbLuaChon.setSelectedIndex(1);
            }
            else if(indexcbSelected == 1)
            {
                txtMaSach.setText((String) model.getValueAt(id, 1));
                txtTenSach.setText((String) model.getValueAt(id, 2));
                btnThem.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_tableHienThiMouseClicked

    private void cbLuaChonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLuaChonItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            indexcbSelected = cbLuaChon.getSelectedIndex();
            txtTimKiem.setText("");
            model.setNumRows(0);
            if(indexcbSelected==0)
            {
                model.setColumnIdentifiers(new Object[]{
                "STT","Mã độc giả","Tên độc giả","Ngày sinh","Giới tính","Địa chỉ","Số điện thoại","Nhóm"
                });
                tableHienThi.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
                tableHienThi.getColumnModel().getColumn(0).setPreferredWidth(45);
                tableHienThi.getColumnModel().getColumn(1).setPreferredWidth(150);
                tableHienThi.getColumnModel().getColumn(2).setPreferredWidth(170);
                tableHienThi.getColumnModel().getColumn(3).setPreferredWidth(120);
                tableHienThi.getColumnModel().getColumn(4).setPreferredWidth(100);
                tableHienThi.getColumnModel().getColumn(5).setPreferredWidth(160);
                tableHienThi.getColumnModel().getColumn(6).setPreferredWidth(135);
                tableHienThi.getColumnModel().getColumn(7).setPreferredWidth(115);
                
                
            }
            else if(indexcbSelected == 1)
            {
                model.setColumnIdentifiers(new Object[]{
                "STT","Mã sách","Tên sách","Tên tác giả","Nơi xuất bản","Năm xuất bản","Loại"
                });
                tableHienThi.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
                tableHienThi.getColumnModel().getColumn(0).setPreferredWidth(45);
                tableHienThi.getColumnModel().getColumn(1).setPreferredWidth(170);
                tableHienThi.getColumnModel().getColumn(2).setPreferredWidth(170);
                tableHienThi.getColumnModel().getColumn(3).setPreferredWidth(170);
                tableHienThi.getColumnModel().getColumn(4).setPreferredWidth(150);
                tableHienThi.getColumnModel().getColumn(5).setPreferredWidth(150);
                tableHienThi.getColumnModel().getColumn(6).setPreferredWidth(140);
            }
        }
    }//GEN-LAST:event_cbLuaChonItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        setEnable(true);
        jButton1.setEnabled(false);
        btnTimKiem.setEnabled(true);
        PhieuMuon phieumuon = new PhieuMuon();
        phieumuon.setMaphieumuon(txtMaPhieuMuon.getText());
        try {
            phieumuon.setNgaymuon(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayMuon.getText()));
        } catch (ParseException ex) {
        }
        try {
            phieumuon.setNgaytra(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayTra.getText()));
        } catch (ParseException ex) {
        }
        list.add(phieumuon);
        new DAO_ChiTietPhieuMuon().addPhieuMuon(phieumuon);
        checkout = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String maphieumuon = txtMaPhieuMuon.getText();
        String madocgia = txtMaDocGia.getText();
        String masach = txtMaSach.getText();
        if(new DAO_ChiTietPhieuMuon().updatePMDocGia(maphieumuon, madocgia))
        {
            if(new DAO_ChiTietPhieuMuon().addChiTietPM(maphieumuon, masach))
            {
                getData(maphieumuon);
            }
        }
        btnThem.setEnabled(false);
        btnNhapTiep.setEnabled(true);
        checkout = 2;
        btnLuu.setEnabled(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnNhapTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapTiepActionPerformed
        clearText();
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnNhapTiep.setEnabled(false);
        cbLuaChon.setSelectedIndex(1);
    }//GEN-LAST:event_btnNhapTiepActionPerformed

    private void tableChiTietPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChiTietPhieuMuonMouseClicked
        int id = tableChiTietPhieuMuon.getSelectedRow();
        if(id>=0)
        {
            
                cbLuaChon.setSelectedIndex(0);
                
                txtMaDocGia.setText((String) model1.getValueAt(id, 2));
                txtTenDocGia.setText((String) model1.getValueAt(id, 3));
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy");  
                String text = df.format(model1.getValueAt(id, 5));
                txtNgayTra.setText(text);
                txtMaSach.setText((String) model1.getValueAt(id, 6));
                txtTenSach.setText((String) model1.getValueAt(id, 7));
                btnThem.setEnabled(false);
                btnXoa.setEnabled(true);
                btnSua.setEnabled(true);
                btnNhapTiep.setEnabled(true);
            
            
        }
    }//GEN-LAST:event_tableChiTietPhieuMuonMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String sophieumuon = txtMaPhieuMuon.getText();
        PhieuMuon phieumuon = new PhieuMuon();
        phieumuon.setMadocgia(txtMaDocGia.getText());
        phieumuon.setMaphieumuon(txtMaPhieuMuon.getText());
        try {
            phieumuon.setNgaytra(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayTra.getText()));
        } catch (ParseException ex) {
        }
        list.add(phieumuon);
        if(new DAO_ChiTietPhieuMuon().updatePM(phieumuon))
        {
            getData(sophieumuon);
            clearText();
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn xóa không","Question",JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {
            String masach = txtMaSach.getText();
            String sophieumuon = txtMaPhieuMuon.getText();
            if(new DAO_ChiTietPhieuMuon().deleteCTPhieuMuon(masach, sophieumuon))
            {
                
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công !","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                getData(sophieumuon); 
                clearText();
                btnSua.setEnabled(false);
                btnXoa.setEnabled(false);
            }
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        if(checkout == 0)
        {
            this.setVisible(false);
            fHeThong hethong = new fHeThong();
            hethong.setLocationRelativeTo(null);
            hethong.setVisible(true);
        }
        else if(checkout == 1)
        {
            int result = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn thoát không. Mọi thông tin sẽ không được lưu lại","Question",JOptionPane.YES_NO_OPTION);
            if(result==JOptionPane.YES_OPTION)
            {
                String sophieumuon = txtMaPhieuMuon.getText();
                if(new DAO_ChiTietPhieuMuon().deletePM(sophieumuon))
                {
                    this.setVisible(false);
                    fHeThong hethong = new fHeThong();
                    hethong.setLocationRelativeTo(null);
                    hethong.setVisible(true);
                }
            }
        }
        else if(checkout == 2)
        {
            int result = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn thoát không. Mọi thông tin sẽ không được lưu lại","Question",JOptionPane.YES_NO_OPTION);
            if(result==JOptionPane.YES_OPTION)
            {
                String sophieumuon = txtMaPhieuMuon.getText();
                if(new DAO_ChiTietPhieuMuon().deleteCTPM(sophieumuon))
                {
                    if(new DAO_ChiTietPhieuMuon().deletePM(sophieumuon))
                    {
                        this.setVisible(false);
                        fHeThong hethong = new fHeThong();
                        hethong.setLocationRelativeTo(null);
                        hethong.setVisible(true);
                    }
                }
                else
                {
                    this.setVisible(false);
                    fHeThong hethong = new fHeThong();
                    hethong.setLocationRelativeTo(null);
                    hethong.setVisible(true);
                }
            }
        }
        else if(checkout == 3)
        {
            this.setVisible(false);
            fHeThong hethong = new fHeThong();
            hethong.setLocationRelativeTo(null);
            hethong.setVisible(true);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        
        JOptionPane.showMessageDialog(rootPane, "Lưu thành công !","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        checkout = 3;
        setEnable(false);
        btnLuu.setEnabled(false);
        btnTimKiem.setEnabled(false);
        btnNhapTiep.setEnabled(false);
    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMuonSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhapTiep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLuaChon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableChiTietPhieuMuon;
    private javax.swing.JTable tableHienThi;
    private javax.swing.JTextField txtMaDocGia;
    private javax.swing.JTextField txtMaPhieuMuon;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtTenDocGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
