/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib_project;

import Controller.DAO_ChiTietPhieuMuon;
import Controller.DAO_PhieuTra;
import Object.ChiTietPhieuTra;
import Object.PhieuMuon;
import Object.PhieuTra;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phuong Thang
 */
public class fTraSach extends javax.swing.JFrame {

    ArrayList<PhieuTra> list = new ArrayList<>();
    ArrayList<PhieuMuon> listphieumuon = new ArrayList<>();
    DefaultTableModel model;
    DefaultTableModel model1;
    public fTraSach() {
        initComponents();
        model = (DefaultTableModel) tableDocGia.getModel();
        model1 = (DefaultTableModel) tablePhieuMuon.getModel();
        resize();
        long now = Instant.now().toEpochMilli();
        txtMaPhieuTra.setText("PT"+String.valueOf(now));
        getDate();
    }
    public final void getDate()
    {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");                                                                                           
        txtNgayTra.setText(sdf.format(date));
    }
    public final void resize()
    {
        tableDocGia.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        tableDocGia.getColumnModel().getColumn(0).setPreferredWidth(60);
        tableDocGia.getColumnModel().getColumn(1).setPreferredWidth(170);
        tableDocGia.getColumnModel().getColumn(2).setPreferredWidth(170);
        tableDocGia.getColumnModel().getColumn(3).setPreferredWidth(140);
        tableDocGia.getColumnModel().getColumn(4).setPreferredWidth(170);
        tableDocGia.getColumnModel().getColumn(5).setPreferredWidth(150);
        tableDocGia.getColumnModel().getColumn(6).setPreferredWidth(150);
        tableDocGia.getColumnModel().getColumn(7).setPreferredWidth(160);
        tableDocGia.getColumnModel().getColumn(8).setPreferredWidth(150);
        
        tablePhieuMuon.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        tablePhieuMuon.getColumnModel().getColumn(0).setPreferredWidth(45);
        tablePhieuMuon.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablePhieuMuon.getColumnModel().getColumn(2).setPreferredWidth(150);
        tablePhieuMuon.getColumnModel().getColumn(3).setPreferredWidth(130);
        tablePhieuMuon.getColumnModel().getColumn(4).setPreferredWidth(120);
        tablePhieuMuon.getColumnModel().getColumn(5).setPreferredWidth(130);
        tablePhieuMuon.getColumnModel().getColumn(6).setPreferredWidth(130);
        tablePhieuMuon.getColumnModel().getColumn(7).setPreferredWidth(150);
        tablePhieuMuon.getColumnModel().getColumn(8).setPreferredWidth(100);
        tablePhieuMuon.getColumnModel().getColumn(9).setPreferredWidth(120);
        tablePhieuMuon.getColumnModel().getColumn(10).setPreferredWidth(100);
    }
    public final void getData(String ten)
    {
        model.setNumRows(0);
        list = new DAO_PhieuTra().getListDocGia(ten);
        int i = 1;
        for(PhieuTra obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMadocgia(),obj.getTendocgia(),obj.getNgaysinh(),obj.getDiachi(),obj.getSdt(),obj.getNhom(),obj.getSophieumuon(),obj.getNgaymuon()
            });
        }
    }
    public final void getDataPhieuMuon(String sophieumuon)
    {
        model1.setNumRows(0);
        listphieumuon = new DAO_ChiTietPhieuMuon().getListPhieuMuon(sophieumuon);
        int i = 1;
        for(PhieuMuon obj:listphieumuon)
        {
            model1.addRow(new Object[]{
            i++, obj.getMaphieumuon(),obj.getMadocgia(),obj.getTendocgia(),obj.getNgaymuon(),obj.getNgaytra(),obj.getMasach(),obj.getTensach()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuMuon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDocGia = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtMaPhieuTra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trả Sách");

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jPanel2.setBackground(new java.awt.Color(230, 136, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trả Sách");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Package-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(581, 581, 581))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tablePhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Số phiếu mượn", "Mã độc giả", "Tên độc giả", "Ngày mượn", "Ngày trả", "Mã sách", "Tên sách", "Nguyên vẹn", "Không nguyên vẹn", "Bị mất"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhieuMuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePhieuMuon);

        tableDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã độc giả", "Tên độc giả", "Ngày sinh", "Địa chỉ", "Số điện thoại", "Nhóm", "Số phiếu mượn", "Ngày mượn"
            }
        ));
        tableDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDocGiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDocGia);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tìm kiếm :");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtMaPhieuTra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã phiếu trả :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ngày trả:");

        txtNgayTra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnLuu.setBackground(new java.awt.Color(51, 153, 255));
        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaPhieuTra, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtMaPhieuTra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThoat)
                        .addComponent(btnLuu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String ten = txtTimKiem.getText();
        getData(ten);
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tablePhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhieuMuonMouseClicked
        
    }//GEN-LAST:event_tablePhieuMuonMouseClicked

    private void tableDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDocGiaMouseClicked
        int id = tableDocGia.getSelectedRow();
        if(id>=0)
        {
            getDataPhieuMuon((String) model.getValueAt(id, 7));
        }
    }//GEN-LAST:event_tableDocGiaMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
            this.setVisible(false);
            fHeThong hethong = new fHeThong();
            hethong.setLocationRelativeTo(null);
            hethong.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed

            ChiTietPhieuTra ctphieutra = new ChiTietPhieuTra();
            ctphieutra.setSophieutra(txtMaPhieuTra.getText());
            ctphieutra.setMabandoc((String) model1.getValueAt(0, 2));
            ctphieutra.setSophieumuon((String) model1.getValueAt(0, 1));
            try {
            ctphieutra.setNgaytra(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayTra.getText()));
            } catch (ParseException ex) {
            }
            ArrayList<ChiTietPhieuTra> listt = new ArrayList<>();
            if(new DAO_PhieuTra().addPhieuTra(ctphieutra))
            {
                for(int i =0;i< model1.getRowCount();i++)
                {
                    ChiTietPhieuTra ctpt = new ChiTietPhieuTra();
                    ctpt.setSophieutra(txtMaPhieuTra.getText());
                    ctpt.setMasach((String) model1.getValueAt(i, 6));
                    
                    try {
                        if((boolean)model1.getValueAt(i,8)==true)
                        {
                            ctpt.setTinhtrang("Nguyên Vẹn");
                        }
                    } catch (Exception e) {
                    }
                    try {
                        if((boolean)model1.getValueAt(i,9)==true)
                        {
                            ctpt.setTinhtrang("Không Nguyên Vẹn");
                        }
                    } catch (Exception e) {
                    }
                    try {
                        if((boolean)model1.getValueAt(i,10)==true)
                        {
                            ctpt.setTinhtrang("Bị Mất");
                        }
                    } catch (Exception e) {
                    }
                    listt.add(ctpt);
                }
            
                for(ChiTietPhieuTra phieu:listt)
                {
                    new DAO_PhieuTra().addCTPhieuTra(phieu);
                }
                JOptionPane.showMessageDialog(rootPane, "Hoàn thành !","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                btnLuu.setEnabled(false);
                
            }
            
                
        
    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fTraSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDocGia;
    private javax.swing.JTable tablePhieuMuon;
    private javax.swing.JTextField txtMaPhieuTra;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
